"use client";

import { useCallback, useMemo, useState } from "react";
import CalculatorLayout from "@/components/CalculatorLayout";
import CalculatorSchema from "@/components/CalculatorSchema";
import BreadcrumbSchema from "@/components/BreadcrumbSchema";
import FAQSection from "@/components/FAQSection";
import RelatedCalculators from "@/components/RelatedCalculators";
import Link from "next/link";
import { lookupZip, fetchHistoricalDaily } from "@/lib/weather";
import { VEGETABLES } from "@/data/vegetables";

interface Task {
  crop: string;
  icon: string;
  kind: "indoor-start" | "harden-off" | "transplant" | "direct-sow";
  date: Date;
}

const KIND_LABEL: Record<Task["kind"], string> = {
  "indoor-start": "Start seeds indoors",
  "harden-off": "Harden off",
  transplant: "Transplant to garden",
  "direct-sow": "Direct sow outdoors",
};

const KIND_EMOJI: Record<Task["kind"], string> = {
  "indoor-start": "🌱",
  "harden-off": "☀️",
  transplant: "🪴",
  "direct-sow": "🌾",
};

function addWeeks(date: Date, weeks: number): Date {
  const next = new Date(date);
  next.setDate(next.getDate() + weeks * 7);
  return next;
}

function fmtDate(d: Date): string {
  return d.toLocaleDateString("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function toIcsDate(d: Date): string {
  // YYYYMMDDTHHmmssZ
  const pad = (n: number) => n.toString().padStart(2, "0");
  return (
    `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}T` +
    `080000Z`
  );
}

function toIcsDateOnly(d: Date): string {
  const pad = (n: number) => n.toString().padStart(2, "0");
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}`;
}

function buildIcs(tasks: Task[], place: string): string {
  const lines: string[] = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//PlantingCalc//Seed Start Calendar//EN",
    "CALSCALE:GREGORIAN",
    `X-WR-CALNAME:Seed Start Calendar — ${place}`,
  ];
  for (const t of tasks) {
    const uid = `${toIcsDateOnly(t.date)}-${t.crop}-${t.kind}@plantingcalc.com`;
    const summary = `${KIND_EMOJI[t.kind]} ${KIND_LABEL[t.kind]}: ${t.crop}`;
    const dstart = toIcsDateOnly(t.date);
    const dend = toIcsDateOnly(addWeeks(t.date, 0));
    // All-day events
    lines.push(
      "BEGIN:VEVENT",
      `UID:${uid}`,
      `DTSTAMP:${toIcsDate(new Date())}`,
      `DTSTART;VALUE=DATE:${dstart}`,
      `DTEND;VALUE=DATE:${dend}`,
      `SUMMARY:${summary}`,
      `DESCRIPTION:Generated by plantingcalc.com/seed-start-calendar for ${place}`,
      "END:VEVENT"
    );
  }
  lines.push("END:VCALENDAR");
  return lines.join("\r\n");
}

export default function SeedStartCalendarPage() {
  const [zip, setZip] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [placeName, setPlaceName] = useState<string | null>(null);
  const [lastFrostDate, setLastFrostDate] = useState<Date | null>(null);

  const runLookup = useCallback(async () => {
    if (!/^\d{5}$/.test(zip)) {
      setError("Enter a 5-digit US ZIP code");
      return;
    }
    setError(null);
    setLoading(true);
    try {
      const loc = await lookupZip(zip);
      if (!loc) {
        setError("Could not look up that ZIP");
        setLoading(false);
        return;
      }
      setPlaceName(loc.place);

      // Compute mean last frost date from last 15 years
      const currentYear = new Date().getFullYear();
      const startYear = currentYear - 15;
      const endYear = currentYear - 1;
      const data = await fetchHistoricalDaily(
        loc.lat,
        loc.lng,
        `${startYear}-02-01`,
        `${endYear}-06-30`
      );
      if (!data || !data.dates.length) {
        setError("Could not load historical weather");
        setLoading(false);
        return;
      }
      // Find last-frost-day-of-year for each year, average
      const byYear: Record<number, number> = {};
      for (let i = 0; i < data.dates.length; i++) {
        if (data.tmin[i] <= 32) {
          const year = Number(data.dates[i].slice(0, 4));
          const date = new Date(data.dates[i]);
          const doy = Math.floor(
            (date.getTime() - new Date(year, 0, 0).getTime()) / 86400000
          );
          if (!byYear[year] || doy > byYear[year]) byYear[year] = doy;
        }
      }
      const years = Object.keys(byYear);
      const avgDoy =
        years.reduce((s, y) => s + byYear[Number(y)], 0) / years.length;
      // Use the CURRENT year for the calendar dates
      const lastFrost = new Date(currentYear, 0, Math.round(avgDoy));
      setLastFrostDate(lastFrost);
    } catch {
      setError("Unexpected error. Try again.");
    } finally {
      setLoading(false);
    }
  }, [zip]);

  const tasks = useMemo<Task[]>(() => {
    if (!lastFrostDate) return [];
    const out: Task[] = [];
    for (const v of VEGETABLES) {
      if (v.indoorStart !== null) {
        out.push({
          crop: v.name,
          icon: v.icon,
          kind: "indoor-start",
          date: addWeeks(lastFrostDate, v.indoorStart),
        });
      }
      if (v.transplant !== null) {
        // Harden off 1 week before transplant
        out.push({
          crop: v.name,
          icon: v.icon,
          kind: "harden-off",
          date: addWeeks(lastFrostDate, v.transplant - 1),
        });
        out.push({
          crop: v.name,
          icon: v.icon,
          kind: "transplant",
          date: addWeeks(lastFrostDate, v.transplant),
        });
      }
      if (v.directSow !== null && v.indoorStart === null) {
        out.push({
          crop: v.name,
          icon: v.icon,
          kind: "direct-sow",
          date: addWeeks(lastFrostDate, v.directSow),
        });
      }
    }
    out.sort((a, b) => a.date.getTime() - b.date.getTime());
    return out;
  }, [lastFrostDate]);

  const handleDownloadIcs = () => {
    if (!tasks.length || !placeName) return;
    const ics = buildIcs(tasks, placeName);
    const blob = new Blob([ics], { type: "text/calendar;charset=utf-8" });
    const href = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = href;
    a.download = `seed-start-${zip}.ics`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(href);
  };

  // Group tasks by month
  const grouped = useMemo(() => {
    const g: Record<string, Task[]> = {};
    for (const t of tasks) {
      const key = t.date.toLocaleDateString("en-US", {
        month: "long",
        year: "numeric",
      });
      (g[key] ??= []).push(t);
    }
    return g;
  }, [tasks]);

  return (
    <CalculatorLayout
      title="Seed Start Calendar"
      description="Enter your ZIP code. Get a full seed starting calendar for 40+ vegetables personalized to your local last-frost date. Download as an ICS file and the dates drop straight into Google Calendar or Apple Calendar."
      answerBlock={
        <p>
          <strong>Quick answer:</strong> Every vegetable has an ideal indoor-start window
          measured in weeks relative to the last frost date. Tomatoes start 6 weeks before;
          peppers 8 weeks; brassicas 6-8 weeks; cucurbits only 3 weeks. This tool looks up
          your ZIP&apos;s actual last-frost date (from the last 15 years of historical
          weather), builds a personalized calendar, and exports every task as an ICS file
          you can drop into any calendar app. No signup, no login, no ads.
        </p>
      }
      lastUpdated="April 2026"
    >
      <CalculatorSchema
        name="Seed Start Calendar"
        description="Personalized indoor seed starting calendar by US ZIP code. Includes ICS calendar file export. Free, no signup."
        url="https://plantingcalc.com/seed-start-calendar"
        featureList={[
          "40+ vegetables",
          "Personalized to your last frost date",
          "ICS calendar file export",
          "Indoor start, harden-off, transplant, direct sow",
          "Free, no signup",
        ]}
      />
      <BreadcrumbSchema
        items={[
          { name: "Home", url: "https://plantingcalc.com" },
          {
            name: "Seed Start Calendar",
            url: "https://plantingcalc.com/seed-start-calendar",
          },
        ]}
      />

      <div className="mb-8">
        <label className="mb-1 block text-sm font-medium text-[var(--color-text)]">
          Your ZIP code
        </label>
        <div className="flex gap-2">
          <input
            type="text"
            inputMode="numeric"
            pattern="\d{5}"
            maxLength={5}
            value={zip}
            onChange={(e) => setZip(e.target.value.replace(/\D/g, ""))}
            onKeyDown={(e) => {
              if (e.key === "Enter") runLookup();
            }}
            placeholder="e.g. 55401"
            className="w-32 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2 text-sm"
          />
          <button
            type="button"
            onClick={runLookup}
            disabled={loading || !zip}
            className="rounded-lg bg-[var(--color-primary)] px-4 py-2 text-sm font-semibold text-white shadow-sm transition-colors hover:opacity-90 disabled:opacity-50"
          >
            {loading ? "Building calendar…" : "Build my calendar"}
          </button>
        </div>
        {error && (
          <p className="mt-2 text-xs text-rose-600" role="alert">
            {error}
          </p>
        )}
        {placeName && lastFrostDate && (
          <p className="mt-2 text-xs text-[var(--color-text-muted)]">
            {placeName} · mean last frost: {fmtDate(lastFrostDate)}
          </p>
        )}
      </div>

      {tasks.length > 0 && (
        <>
          <div className="mb-6 flex flex-wrap gap-3">
            <button
              type="button"
              onClick={handleDownloadIcs}
              className="inline-flex items-center gap-2 rounded-lg bg-[var(--color-primary)] px-4 py-2 text-sm font-semibold text-white shadow-sm transition-colors hover:opacity-90"
            >
              📥 Download calendar (.ics)
            </button>
            <span className="text-xs text-[var(--color-text-muted)] self-center">
              {tasks.length} events · compatible with Google, Apple, Outlook
            </span>
          </div>

          <div className="space-y-6">
            {Object.entries(grouped).map(([month, items]) => (
              <div
                key={month}
                className="overflow-hidden rounded-xl border border-[var(--color-border)] bg-white"
              >
                <div className="border-b border-[var(--color-border)] bg-[var(--color-surface-alt)] px-5 py-2.5">
                  <h3 className="font-bold text-[var(--color-text)]">{month}</h3>
                </div>
                <ul className="divide-y divide-[var(--color-border)]">
                  {items.map((t, i) => (
                    <li
                      key={`${t.crop}-${t.kind}-${i}`}
                      className="flex items-center gap-3 px-5 py-2.5 text-sm"
                    >
                      <span className="text-lg">{t.icon}</span>
                      <span className="w-24 text-[var(--color-text-muted)]">
                        {t.date.toLocaleDateString("en-US", {
                          weekday: "short",
                          month: "short",
                          day: "numeric",
                        })}
                      </span>
                      <span className="text-xs text-[var(--color-text-muted)]">
                        {KIND_EMOJI[t.kind]} {KIND_LABEL[t.kind]}
                      </span>
                      <span className="font-medium text-[var(--color-text)]">
                        {t.crop}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </>
      )}

      <div className="mt-6 flex flex-wrap gap-3 text-sm">
        <Link
          href="/planting-dates"
          className="rounded-lg border border-[var(--color-border)] px-3 py-2 text-[var(--color-primary)] transition-colors hover:bg-[var(--color-primary)]/5"
        >
          Planting dates by crop →
        </Link>
        <Link
          href="/frost-probability"
          className="rounded-lg border border-[var(--color-border)] px-3 py-2 text-[var(--color-primary)] transition-colors hover:bg-[var(--color-primary)]/5"
        >
          Frost probability for any date →
        </Link>
        <Link
          href="/plant-today"
          className="rounded-lg border border-[var(--color-border)] px-3 py-2 text-[var(--color-primary)] transition-colors hover:bg-[var(--color-primary)]/5"
        >
          Can I plant today? →
        </Link>
      </div>

      <FAQSection questions={seedStartFAQ} />
      <RelatedCalculators currentPath="/seed-start-calendar" />
    </CalculatorLayout>
  );
}

const seedStartFAQ = [
  {
    question: "Will the ICS file really work with Google Calendar and Apple Calendar?",
    answer:
      "Yes. The file uses the standard RFC 5545 iCalendar format, which is what Google, Apple, and Outlook all use natively. Google Calendar: import via Settings → Import & export. Apple Calendar: double-click the .ics file. Outlook: File → Open & Export → Import/Export. All 40+ events get added as all-day entries on the right dates, with emoji in the title so they're easy to spot.",
  },
  {
    question: "Where does the last-frost date come from?",
    answer:
      "It's computed fresh for your ZIP from the last 15 years of daily temperature records. The tool looks up your ZIP's lat/lng, pulls 15 years of daily minimums from the ECMWF ERA5 reanalysis, finds the last spring day in each year that hit 32°F or below, and averages those dates. That's the 50th percentile last-frost date. It automatically reflects recent warming because it always uses the most recent 15 years.",
  },
  {
    question: "Does this handle fall plantings too?",
    answer:
      "Not yet. This tool focuses on the spring seed start window because that's where planning leverage is highest. Fall plantings depend on the FIRST frost date and season length, which is a separate calculation. A fall succession planner is on the roadmap.",
  },
  {
    question: "Why does it suggest hardening off a week before transplant?",
    answer:
      "Seedlings raised indoors have soft, thin cuticles and no UV-adaptation. Moving them straight from a windowsill to full sun typically kills half the leaves and stunts growth for 2-3 weeks. Hardening off means putting them outside in shade for an hour or two, then gradually lengthening the time and exposure over 7-10 days. This tool schedules a harden-off reminder exactly a week before each transplant date so you don't skip the step.",
  },
  {
    question: "My zone is 6b but I'm in a frost pocket. Should I adjust?",
    answer:
      "Yes, by about 1-2 weeks. Frost pockets (low-lying areas where cold air settles overnight) typically see last frost 10-14 days later than the ZIP average, and first frost 10-14 days earlier. If you know you're in a frost pocket, treat every transplant date in this calendar as being ~2 weeks too early and adjust. South-facing slopes and urban heat islands work in the opposite direction: you can safely subtract a week.",
  },
];
